### PR TITLE
998 env variables are used before initialised by dotenv

### PR DESCRIPTION
**Pull request by Defferrard**
The first implementation of #998 didn't solved the issue. Because environnement variables where still used before initialisation during test context.

I've moved every `process.env`declarations in `config.ts` file, so every time we need to fetch an environnement variable, we have to import the configuration file.

### CODE REVIEW

**Review by spaenleh — APPROVED** [review]
LGTM ! thank you !

**Comment by spaenleh** [comment]
@Defferrard You seem to have an error with an undefined `COOKIE_DOMAIN` env.

**Comment by Defferrard** [comment]
> @Defferrard You seem to have an error with an undefined `COOKIE_DOMAIN` env.

It seems like the `build-node` only define the needed environnement variable to run the `src/plugins/datasource.ts` file. Which originaly use `process.env`to fetch the environnement variable.

Now with my modification, it imports `config.ts`, and needs to define **all** environnement variable needed to run the whole application.

Which means I can either :
1. **Set a default value to every constants in `config.ts``** I'd use development variable, so we wouldn't need a `.env.development` with 130 line. But it wouldn't throw an error anymore if we don't define an mandatory variable.
2. **Define all environnement variable in `build-node` job.** Which is already done in `test-node` job.

Any preference, or suggestions @spaenleh , @pyphilia  ?

**Review by spaenleh — APPROVED** [review]
🚀

**Review by pyphilia — APPROVED** [review]
So cool, LGTM 💯

**Pull request merged**
